# Generated by Django 2.1 on 2022-08-07 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
